###
GET localhost:8080/api/v1/activities
Accept: application/json

###
GET localhost:8080/api/v1/activities/5
Accept: application/json

###
POST localhost:8080/api/v1/activities
Accept: application/json
Content-Type: application/json

{
  "name": "Third",
  "description": "Third task",
  "streak_count": 2
}

###
PUT localhost:8080/api/v1/activities/10
Accept: application/json
Content-Type: application/json

{
  "name": "Bismillah leetcode selesai",
  "description": "AAAAA",
  "streak_count": 1
}

###
DELETE localhost:8080/api/v1/activities/11
Accept: application/json

###
GET localhost:8080/api/v1/logs
Accept: application/json

###
GET localhost:8080/api/v1/logs/10
Accept: application/json

###
POST localhost:8080/api/v1/logs
Accept: application/json
Content-Type: application/json

{
  "description": "First log",
  "count": 1,
  "completed_at": "2024-04-25T14:32:57.809118+07:00",
  "activity_id": 1
}

###
PUT localhost:8080/api/v1/logs/4
Accept: application/json
Content-Type: application/json

{
  "description": "Fourth log",
  "count": 5,
  "completed_at": "2024-04-25T14:32:57.809118+07:00",
  "activity_id": 3
}

###
DELETE localhost:8080/api/v1/logs/6
Accept: application/json